
find_path(MBEDTLS_INCLUDE_DIR
	NAMES mbedtls/ssl.h
	PATH_SUFFIXES include
	HINTS ${MBEDTLS_ROOT})

find_library(MBEDTLS_LIBRARY
	NAMES mbedtls
	PATH_SUFFIXES lib
	HINTS ${MBEDTLS_ROOT})

find_library(MBEDCRYPTO_LIBRARY
	NAMES mbedcrypto
	PATH_SUFFIXES lib
	HINTS ${MBEDTLS_ROOT})

find_library(MBEDX509_LIBRARY
	NAMES mbedx509
	PATH_SUFFIXES lib
	HINTS ${MBEDTLS_ROOT})

if(WIN32)
	find_library(MBEDTLS_DEBUG_LIBRARY
		NAMES mbedtlsd
		PATH_SUFFIXES lib
		HINTS ${MBEDTLS_ROOT})

	find_library(MBEDCRYPTO_DEBUG_LIBRARY
		NAMES mbedcryptod
		PATH_SUFFIXES lib
		HINTS ${MBEDTLS_ROOT})

	find_library(MBEDX509_DEBUG_LIBRARY
		NAMES mbedx509d
		PATH_SUFFIXES lib
		HINTS ${MBEDTLS_ROOT})
endif()

if(MBEDTLS_INCLUDE_DIR AND MBEDTLS_LIBRARY)
	set(MBEDTLS_FOUND TRUE)
	set(MBEDTLS_LIBRARIES mbedtls mbedcrypto mbedx509)

	add_library(mbedtls STATIC IMPORTED)
	set_property(TARGET mbedtls PROPERTY IMPORTED_LOCATION ${MBEDTLS_LIBRARY})

	if(MBEDTLS_DEBUG_LIBRARY)
		set_property(TARGET mbedtls PROPERTY IMPORTED_LOCATION_DEBUG ${MBEDTLS_DEBUG_LIBRARY})
	endif()

	add_library(mbedcrypto STATIC IMPORTED)
	set_property(TARGET mbedcrypto PROPERTY IMPORTED_LOCATION ${MBEDCRYPTO_LIBRARY})

	if(MBEDCRYPTO_DEBUG_LIBRARY)
		set_property(TARGET mbedcrypto PROPERTY IMPORTED_LOCATION_DEBUG ${MBEDCRYPTO_DEBUG_LIBRARY})
	endif()

	add_library(mbedx509 STATIC IMPORTED)
	set_property(TARGET mbedx509 PROPERTY IMPORTED_LOCATION ${MBEDX509_LIBRARY})

	if(MBEDX509_DEBUG_LIBRARY)
		set_property(TARGET mbedx509 PROPERTY IMPORTED_LOCATION_DEBUG ${MBEDX509_DEBUG_LIBRARY})
	endif()
endif()

if(MBEDTLS_FOUND)
	if(NOT MBEDTLS_FIND_QUIETLY)
		message(STATUS "Found mbed TLS: ${MBEDTLS_LIBRARIES}")
	endif()
else()
	if(NOT MBEDTLS_FIND_QUIETLY)
		message(STATUS "mbed TLS was not found")
	endif()
endif()

mark_as_advanced(MBEDTLS_INCLUDE_DIR MBEDTLS_LIBRARY)

